[env]
ENV_DIR = {source="${CARGO_MAKE_PROFILE}", default_value = "debug", mapping = {release = "release"}}
CARGO_WASM_PATH = "target/wasm32-unknown-unknown/${ENV_DIR}/${CARGO_MAKE_CRATE_NAME}.wasm"
CARGO_MANIFEST_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}"

[env.release]
CARGO_RELEASE_ARGS = "--release"

[tasks.basic-http-server]
command = "cargo"
args = ["install", "basic-http-server", "--root=bin"]

[tasks.wasm-bindgen-cli]
command = "cargo"
args = ["install", "wasm-bindgen-cli", "--version", "0.2.69", "--root=bin"]

[tasks.cargo-build-web]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown", "@@split(CARGO_RELEASE_ARGS, )"]

[tasks.build-web]
dependencies = ["cargo-build-web", "wasm-bindgen-cli"]
command = "./bin/bin/wasm-bindgen"
args = ["--out-dir", "scripts", "--out-name", "wasm", "--target", "web", "--no-typescript", "${CARGO_WASM_PATH}"]

[tasks.build-native]
command = "cargo"
args = ["build", "@@split(CARGO_RELEASE_ARGS, )"]

[tasks.run]
command = "target/${ENV_DIR}/${CARGO_MAKE_CRATE_NAME}"
dependencies = ["build-native"]

[tasks.serve]
command = "basic-http-server"
args = ["-x"]
dependencies = ["build-web", "basic-http-server"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.pckg-web]
script = '''
mkdir -p page
cp -r scripts page
cp index.html page
cp -r assets page
'''