name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          target/
          bin/
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('Cargo.toml') }}
        restore-keys: ${{ runner.os }}-cargo-build
    - name: Install Dependencies
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
    - name: Install cargo make
      run: cargo install cargo-make --version=0.35.7
    - name: Build wasm and js
      run: |
        cargo make --profile release build-web
        cargo make pckg-web
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: page

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('Cargo.toml') }}
          restore-keys: ${{ runner.os }}-cargo-test
      - name: Run tests
        run: cargo test
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: build-output
        path: pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.WEB_DEPLOY_KEY }}
        external_repository:  psvri/aoc-visuals-website 
        publish_dir: ./pages

